### PR TITLE
Create Report

### PR DESCRIPTION
**Pull request by hankunxiao**
1.	Report Folder:
	•	A new report folder is created to organize all report-related files.
2.	References:
	•	A references.bib file is added to manage all citations for the report.
3.	Quarto Report File:
	•	A .qmd file is added for creating and rendering the report.
4.	Rendered PDF Report:
	•	The rendered PDF report is included as an output.

### CODE REVIEW

**Comment by y1chi-z** [comment]
Thanks for all the work and it looks great! 
Just a few things that I noticed:
- [x] might need to change the date to 2024-12-07
- [x] cite the python programming language in line 62 
- [ ] should we update the writing (especially for the introduction) based on TA's comments in Milestone 1?

**Comment by hankunxiao** [comment]
> Thanks for all the work and it looks great! Just a few things that I noticed:
> 
> * [x]  might need to change the date to 2024-12-07
> * [x]  cite the python programming language in line 62
> * [ ]  should we update the writing (especially for the introduction) based on TA's comments in Milestone 1?

Hi Essie, thanks for reviewing my code and I appreciate your feedback.
I have updated the date and added reference to python 3.
For incorporating the TA's comments from milestone 1, I believe it would be an action item in the upcoming milestone.

**Comment by y1chi-z** [comment]
Great! Should I merge the pull request or wait for feedback from Ben and Mason?

**Comment by hankunxiao** [comment]
> Great! Should I merge the pull request or wait for feedback from Ben and Mason?

I think we are good to go.

**Pull request merged**
