### PR TITLE
update data validation

### PR DESCRIPTION
**Pull request by y1chi-z**
1. update the data validation code
- checked data types in each column
- checked empty observations
- checked duplicate observations
- checked missingness (not beyond 15%)
- checked variables' ranges (outliers, category levels)
(to be discuss...
a.  Target/response variable follows expected distribution
b. No anomalous correlations between target/response variable and features/explanatory variables
c. No anomalous correlations between features/explanatory variables
)
2. update the `validation_error.log` file

### CODE REVIEW

**Review by MasonZhang-MZ — COMMENTED** [review]
Thank you for starting out the data validation process @y1chi-z . Here's a suggestion to be reviewed:

Per our discussion from earlier, removing the commented out code in `schema` might be a good idea to reduce redundancy once we confirm the order of data validation and dropping columns with large number of missing values. (e.g. `cap-surface`, `gill-attachment`, `gill-spacing`, `stem-root`, `stem-surface`, `veil-type`, `veil-color`, and `spore-print-color`).

**Comment by y1chi-z** [comment]
Updated the schema and added the distribution and correlation check

**Comment by MasonZhang-MZ** [comment]
Couple comments:

1. Dropping columns based on a certain threshold might be best implemented with `.columns[X.isnull().mean() <= missing_threshold]` for consistency and scalability. But we've manually dropped them in the previous step, so there's no need to change anything at this moment.
2. Great to learn that `validation_error.log` is such a handy way for debugging.
3. Trivial: For Target Variable Visualization, adding value annotations on top of the bars could help with identifying class imbalance.

**Comment by hankunxiao** [comment]
Nice work @y1chi-z ! Thank you so much. 🎉 🎉 
I have a few feedback for you:

1. I agree with @MasonZhang-MZ  about removing the commented-out code to enhance readability. I noticed that you’ve made the updates and committed them to your branch. Could you please raise another pull request so we can incorporate your contributions?
2. I noticed that you set up the `pa.DataFrameSchema` and added our constraints. If you could include a brief inline comment before each column constraint, it would be very helpful for readers without domain knowledge to understand what each constraint does.
3. I noticed that you defined `pa.DataFrameSchema` again in the log generation section. I was wondering if we could reuse the variable from the previous part. This would enhance consistency, especially if we need to update the `pa.DataFrameSchema` in the future.
4. I really appreciate your excellent work in the notebook. Could you render the file to HTML and keep it updated in our GitHub repository?

**Comment by hankunxiao** [comment]
I have another note that I forgot to mention. @y1chi-z 
As we have set up the conda lock and docker. I think we don't need this instruction in our jupyter notebook on how to import the dataset anymore. We can remove it maybe.
 
image

**Comment by y1chi-z** [comment]
Thanks for the feedback. I made a few updates according to the comments:

1. removed the commented-out code ✅
2. added inline comments about constraints ✅
3. unfortunately we will have to define the schema again and set `drop_invalid_rows = False` to track the errors
4. rendered the file to HTML ✅

**Comment by hankunxiao** [comment]
> Thanks for the feedback. I made a few updates according to the comments:
> 
> 1. removed the commented-out code ✅
> 2. added inline comments about constraints ✅
> 3. unfortunately we will have to define the schema again and set `drop_invalid_rows = False` to track the errors
> 4. rendered the file to HTML ✅

thanks @y1chi-z ! I have merged the code to the main branch.

**Pull request merged**
